version: '3.7'
services:
  api:
    build:
      context: app
    container_name: tensor-trigger-api
    ports:
    - "10988:10988"
    networks:
    - tensor-trigger
    - postgres
    - rabbit
    env_file:
      - app/env.list

  worker:
    build:
      context: worker
    container_name: tensor-trigger-worker
    networks:
    - tensor-trigger
    - postgres
    - rabbit
    env_file:
      - app/env.list

networks:
  postgres:
    name: postgres
  tensor-trigger:
    name: tensor-trigger
  rabbit:
    name: rabbit