apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tensor-trigger.fullname" . }}-env
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  postgres_password: {{ .Values.secrets.postgres_password | b64enc }}
  message_broker_url: {{ .Values.secrets.message_broker_url | b64enc }}
  aws_access_key_id: {{ .Values.secrets.aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .Values.secrets.aws_secret_access_key | b64enc }}