apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensor-trigger.fullname" . }}
  labels:
    {{- include "tensor-trigger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tensor-trigger.selectorLabels" . | nindent 4 }}
    app: {{ include "tensor-trigger.name" . }}-api
