name: ci

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to ASN registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          
      - name: Build and push
        run: |
          docker build -t docker.alpinesoftware.net/tensor-trigger/app:latest app
          docker push docker.alpinesoftware.net/tensor-trigger/app:latest

      - name: Build and push
        run: |
          docker build -t docker.alpinesoftware.net/tensor-trigger/worker:latest worker
          docker push docker.alpinesoftware.net/tensor-trigger/worker:latest
